Akis & Manoj - View an individual profile
boolean-uk/team-dev-client-C8_C9 pull request #14
Opened 2023-02-08 12:54 UTC by Akis-Hajittofi

2023-02-08 13:06 UTC, vherus requested changes
This is a good step but there are some changes to consider before bringing this into main

2023-02-08 13:06 UTC, vherus commented on src/App.js
> +}
Let's remove this

2023-02-08 13:06 UTC, vherus commented on src/App.js
> +              path={`error-message`}
`http://localhost:3000/error-message` isn't a very nice URL. I'm not a fan of having a dedicated page for an error message, it should really be a component that displays on the screen the user is already on (e.g. a banner across the top of the page, a pop-up toast bar in the bottom corner, a message close to the element that caused the error etc.)

If you want to go ahead with this, let's at least rename the route to `error` instead of `error-message`

2023-02-08 13:06 UTC, vherus commented on src/components/navigation/index.js
> +          <NavLink to="/">
Should this navlink `to` change to the current users profile now?

2023-02-08 13:06 UTC, vherus commented on src/pages/viewProfile/index.js
> +};
Let's move this object to its own file to clean things up a bit. There's a `mockData.js` file in the `service` directory that could be used

2023-02-08 13:06 UTC, vherus commented on src/pages/viewProfile/index.js
> +  const token = localStorage.getItem("token");
You can get the current users token from the `useAuth()` hook, e.g. `const { token } = useAuth()`

2023-02-08 13:06 UTC, vherus commented on src/pages/viewProfile/index.js
> +  };
There are going to be multiple places where getting the current logged in users data will be used. I recommend this kind of functionality should be moved to the AuthProvider in `src/context/auth.js`. Review the code in there to see how it works.

The token is set in there when a user logs in, registers & completes the create profile step, or loads the app for the first time and a token is loaded from localStorage. You can add some functionality to not only save the token in the context state but also save the user's data in context state

2023-02-08 13:06 UTC, vherus commented on src/pages/viewProfile/index.js
> +  }, [id]);
Please use the apiClient that already exists in `service/apiClient` - it has all of this stuff pre-built so you can simplify this stuff

2023-02-08 13:06 UTC, vherus commented on src/pages/viewProfile/index.js
> +    navigate(`/profile/edit/${id}`);
This should be `/profile/${id}/edit`

2023-02-09 10:10 UTC, vherus approved these changes
LGTM!

2023-02-09 10:31 UTC, Benjipictor approved these changes

2023-02-09 10:32 UTC, merged